language: perl

perl:
    - "5.20"
#    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

notifications:
  irc:
    channels:
      - "irc.perl.org#perl.pt"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    use_notice: true

install:
    - cpanm --installdeps .   || { cat ~/.cpanm/build.log ; false ; }
    - cpanm .                 || { cat ~/.cpanm/build.log ; false ; }

script:
    - ./Build test
